services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "3000:5173"
    volumes:
      - ./frontend/vite-project:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped